[profile.default]
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
out = "out"
solc = "0.8.20"
src = "src"

[profile.ci]
verbosity = 4

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}"}

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
override_spacing = true
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[fuzz]
runs = 1000

[invariant]
depth = 100
fail_on_revert = true
runs = 1000
